<!DOCTYPE html>
<html lang="de" class="">
	
	<head>
	
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
	

    <title>bc547.de - 100 wichtige Bibelstellen</title>

	<link href='https://fonts.googleapis.com/css?family=Press+Start+2P' rel='stylesheet' type='text/css'>
    <link href="http://www.bc547.de/infotechnik/css/jquery.fancybox.min.css" rel="stylesheet">
    <link href="http://www.bc547.de/infotechnik/css/bootstrap.min.css" rel="stylesheet">
	<link href="/grenzwissenschaften/css/grenz.css" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" type="text/css" href="http://www.bc547.de/infotechnik/css/prettify.css">
	
	<style type="text/css">.fancybox-margin{margin-right:14px;}</style>
	
	<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js'></script>
		
	</head>
	<body>

		<div id="header">
			<div id="header-bg">
				<div class="container">
					<div class="jumbotron">
						<h1><img src="/grenzwissenschaften/gfx/header.png" alt="BC547.DE"></h1>
						
					</div>
				</div>
			</div>
		</div>

		<div id="content">

			<div class="container">
				<div class="row">
				
					<div class="col-lg-3">
						<div class="well">
							<div id="subnavigation" class="altcolor">
								<div class="gutter">
									<div data-container="navigation">
										<div class="j-nav-variant-standard"></div>
									</div>
								</div>
						
								<?php include ("./sidebar.inc.php"); ?>
							</div>
						</div>
					</div>
				
					<div class="col-lg-9">
						<div class="well">
							<h2>100 wichtige Bibeltexte</h2>
												
												<p>Es ist nicht wichtig die ganze Bibel auswendig zu kennen, sondern es ist klüger das Wesentliche zu beherzigen. Aus diesem Grund bietet diese Seite eine Übersicht zu 100 wichtigen Bibelstellen, die man kennen sollte. Am besten man druckt sie aus und liest sie regelmäßig, damit sie in Herz und Kopf übergehen.
												</p>
												<p>Download: als <a href="/grenzwissenschaften/pdf/100_wichtige_Bibeltexte.pdf">PDF</a> oder im <a href="/grenzwissenschaften/pdf/100_wichtige_Bibeltexte.odt">OpenDocument</a> Format.</p>

												<ol>
												<li>»Behandelt die Menschen so, wie ihr selbst von ihnen behandelt werden wollt - das ist es, was das Gesetz und die Propheten fordern.« (<span class="t2">GNB</span> - <span class="t1">Matthäus 7:12</span>)<p>
												</p></li><li>Bleibt niemandem etwas schuldig, abgesehen von der Liebe, die ihr einander immer schuldig seid. Denn wer den anderen liebt, hat damit das Gesetz Gottes erfüllt. Die Gebote gegen Ehebruch, Mord, Diebstahl und Begehren sind - wie auch alle anderen Gebote - in diesem einen Gebot zusammengefasst: »Liebe deinen Nächsten wie dich selbst.« Die Liebe fügt niemandem Schaden zu; deshalb ist die Liebe die Erfüllung von Gottes Gesetz. (<span class="t2">NLB</span> - <span class="t1">Römer 13:8-10</span>)<p>
												</p></li><li>Lebt nach dem wichtigsten Gebot in Gottes neuer Welt: "Liebe deinen Mitmenschen wie dich selbst!" Wenn ihr das in die Tat umsetzt, handelt ihr richtig. Beurteilt ihr dagegen Arme und Reiche nach unterschiedlichen Maßstäben, dann verstoßt ihr gegen Gottes Gebot und werdet schuldig. (<span class="t2">HFA</span> - <span class="t1">Jakobus 2:8,9</span>)<p>
												</p></li><li>Wer nicht liebt, hat Gott nicht erkannt; denn Gott ist Liebe. Dadurch ist Gottes Liebe unter uns offenbar geworden, dass er seinen einzigen Sohn in die Welt sandte. Durch ihn wollte er uns das neue Leben schenken. Das Einzigartige an dieser Liebe ist: Nicht wir haben Gott geliebt, sondern er hat uns geliebt. Er hat seinen Sohn gesandt, damit er durch seinen Tod Sühne leiste für unsere Schuld. Ihr Lieben, wenn Gott uns so sehr geliebt hat, dann müssen auch wir einander lieben. (<span class="t2">GNB</span> - <span class="t1">1. Johannes 4:8-11</span>)<p>
												</p></li><li>Meine Brüder und Schwestern, was hat es für einen Wert, wenn jemand behauptet: »Ich vertraue auf Gott, ich habe Glauben!«, aber er hat keine guten Taten vorzuweisen? Kann der bloße Glaube ihn retten? Nehmt einmal an, bei euch gibt es einen Bruder oder eine Schwester, die nichts anzuziehen haben und hungern müssen. Was nützt es ihnen, wenn dann jemand von euch zu ihnen sagt: »Ich wünsche euch das Beste; ich hoffe, dass ihr euch warm anziehen und satt essen könnt!« -, aber er gibt ihnen nicht, was sie zum Leben brauchen? Genauso ist es auch mit dem Glauben: Wenn er allein bleibt und aus ihm keine Taten hervorgehen, ist er tot. Ihr seht also, dass ein Mensch aufgrund seiner Taten von Gott als gerecht anerkannt wird und nicht schon durch bloßen Glauben. (<span class="t2">GNB</span> - <span class="t1">Jakobus 2:14-17,24</span>)<p>
												</p></li><li>Sollte nun jemand behaupten: "Ich liebe Gott", und dabei seinen Bruder oder seine Schwester hassen, dann ist er ein Lügner. Wenn er schon seine Geschwister nicht liebt, die er sehen kann, wie will er dann Gott lieben, den er nicht sieht? Vergesst nicht, dass Christus selbst uns aufgetragen hat: Wer Gott liebt, der muss auch seinen Bruder und seine Schwester lieben. (<span class="t2">HFA</span> - <span class="t1">1. Johannes 4:20,21</span>)<p>
												</p></li><li>Wer seinen Bruder hasst, ist ein Mörder. Und ihr wisst, dass kein Mörder das ewige Leben in sich trägt. (<span class="t2">NLB</span> - <span class="t1">1. Johannes 3:15</span>)<p>
												</p></li><li>Es wurde dir, Mensch, doch schon längst gesagt, was gut ist und wie Gott möchte, dass du leben sollst. Er fordert von euch nichts anderes, als dass ihr euch an das Recht haltet, liebevoll und barmherzig miteinander umgeht und demütig vor Gott euer Leben führt. (<span class="t2">NLB</span> - <span class="t1">Micha 6:8</span>)<p>
												</p></li><li>Schließlich, meine lieben Brüder und Schwestern, orientiert euch an dem, was wahrhaftig, gut und gerecht, was redlich und liebenswert ist und einen guten Ruf hat, an dem, was auch bei euren Mitmenschen als Tugend gilt und Lob verdient. (<span class="t2">HFA</span> - <span class="t1">Philipper 4:8</span>)<p>
												</p></li><li>Weg also mit aller Verbitterung, mit Aufbrausen, Zorn und jeder Art von Beleidigung! Schreit einander nicht an! Legt jede feindselige Gesinnung ab! (<span class="t2">GNB</span> - <span class="t1">Epheser 4:31</span>)<p>
												</p></li><li>Lasst ja kein giftiges Wort über eure Lippen kommen! Seht lieber zu, dass ihr für die anderen, wo es nötig ist, ein gutes Wort habt, das weiterhilft und denen wohl tut, die es hören. (<span class="t2">GNB</span> - <span class="t1">Epheser 4:29</span>)<p>
												</p></li><li>Macht darum Schluss mit allem, was unrecht ist! Hört auf zu lügen und euch zu verstellen, andere zu beneiden oder schlecht über sie zu reden. (<span class="t2">GNB</span> - <span class="t1">1. Petrus 2:1</span>)<p>
												</p></li><li>Ihr wisst ja: »Wer nach dem wahren Leben verlangt und glückliche Tage sehen will, der nehme seine Zunge gut in Acht, dass er nichts Schlechtes und Hinterhältiges sagt.« (<span class="t2">GNB</span> - <span class="t1">1. Petrus 3:10</span>)<p>
												</p></li><li>Ich sage euch das, weil ihr am Gerichtstag Rechenschaft ablegen müsst über jedes unnütze Wort, das ihr geredet habt. Eure Worte sind der Maßstab, nach dem ihr freigesprochen oder verurteilt werdet. (<span class="t2">HFA</span> - <span class="t1">Matthäus 12:36,37</span>)<p>
												</p></li><li>Ein Mensch, der viel redet, versündigt sich leicht; wer seine Zunge im Zaum hält, zeigt Verstand. (<span class="t2">GNB</span> - <span class="t1">Sprüche 10:19</span>)<p>
												</p></li><li>Wer seine Zunge im Zaum halten kann, schützt sich selbst. Ein Großmaul richtet sich zugrunde. (<span class="t2">HFA</span> - <span class="t1">Sprüche 13:3</span>)<p>
												</p></li><li>Die Worte eines gedankenlosen Schwätzers verletzen wie Messerstiche; was ein weiser Mensch sagt, heilt und belebt. (<span class="t2">HFA</span> - <span class="t1">Sprüche 12:18</span>)<p>
												</p></li><li>Wenn du wirklich etwas gelernt hast, gehst du sparsam mit deinen Worten um. Ein Mensch, der sich beherrschen kann, zeigt, dass er Verstand hat. Sogar ein Dummkopf kann für klug und verständig gehalten werden &ndash; wenn er nur den Mund halten könnte! (<span class="t2">GNB</span> - <span class="t1">Sprüche 17:27,28</span>)<p>
												</p></li><li>Der Dummkopf gibt jedem Ärger freien Lauf; der Weise kann sich beherrschen. (<span class="t2">GNB</span> - <span class="t1">Sprüche 29:11</span>)<p>
												</p></li><li>Nimm keinen Jähzornigen zum Freund und verkehre nicht mit jemand, der sich nicht beherrschen kann. Sonst gewöhnst du dich an seine Unart und gefährdest dein Leben. (<span class="t2">GNB</span> - <span class="t1">Sprüche 22:24,25</span>)<p>
												</p></li><li>Ein Biertrinker wird unangenehm laut, und ein Weinsäufer redet Blödsinn; wer sich betrinkt, ist unvernünftig! (<span class="t2">HFA</span> - <span class="t1">Sprüche 20:1</span>)<p>
												</p></li><li>Willst du wissen, wer ständig stöhnt und sich selbst bemitleidet? Wer immer Streit hat und sich über andere beklagt? Wer glasige Augen hat und Verletzungen, die er sich hätte ersparen können? Das sind die, die bis spät in die Nacht beim Wein sitzen und keine Gelegenheit auslassen, eine neue Mischung zu probieren. Lass dich nicht vom Wein verführen! Er funkelt so rot im Becher und gleitet so angenehm durch die Kehle; aber dann wird es dir schwindlig, als hätte dich eine giftige Schlange gebissen. Du siehst Dinge, die es gar nicht gibt, und redest dummes Zeug. (<span class="t2">GNB</span> - <span class="t1">Sprüche 23:29-33</span>)<p>
												</p></li><li>»Ihr wisst auch, dass unseren Vorfahren gesagt worden ist: Ihr sollt keinen Meineid schwören und sollt halten, was ihr Gott mit einem Eid versprochen habt. Ich aber sage euch: Ihr sollt überhaupt nicht schwören! Nehmt weder den Himmel zum Zeugen, denn er ist Gottes Thron, noch die Erde, denn sie ist sein Fußschemel, und auch nicht Jerusalem, denn es ist die Stadt des himmlischen Königs. Nicht einmal mit eurem eigenen Kopf sollt ihr euch für etwas verbürgen; denn es steht nicht in eurer Macht, dass auch nur ein einziges Haar darauf schwarz oder weiß wächst. Sagt einfach Ja oder Nein; jedes weitere Wort stammt vom Teufel.« (<span class="t2">GNB</span> - <span class="t1">Matthäus 5:33-37</span>)<p>
												</p></li><li>Vor allem, meine Brüder und Schwestern, lasst das Schwören, wenn ihr irgendetwas beteuern wollt. Schwört weder beim Himmel noch bei der Erde noch bei sonst etwas. Euer Ja muss ein Ja sein und euer Nein ein Nein. Sonst verfallt ihr dem Gericht Gottes. (<span class="t2">GNB</span> - <span class="t1">Jakobus 5:12</span>)<p>
												</p></li><li>Dankt Gott, dem Vater, zu jeder Zeit für alles im Namen unseres Herrn Jesus Christus. (<span class="t2">GNB</span> - <span class="t1">Epheser 5:20</span>)<p>
												</p></li><li>Plappert nicht vor euch hin, wenn ihr betet, wie es die Menschen tun, die Gott nicht kennen. Sie glauben, dass ihre Gebete erhört werden, wenn sie die Worte nur oft genug wiederholen. Seid nicht wie sie, denn euer Vater weiß genau, was ihr braucht, noch bevor ihr ihn darum bittet! (<span class="t2">NLB</span> - <span class="t1">Matthäus 6:7,8</span>)<p>
												</p></li><li>Meint ihr, der Arm des Herrn sei zu kurz, um euch zu helfen, oder der Herr sei taub und könne euren Hilferuf nicht hören? Nein, sondern wie eine Mauer steht eure Schuld zwischen euch und eurem Gott; wegen eurer Vergehen hat er sich von euch abgewandt und hört euch nicht! (<span class="t2">GNB</span> - <span class="t1">Jesaja 59:1,2</span>)<p>
												</p></li><li>Wer der Versuchung erliegt, sollte niemals sagen: »Diese Versuchung kommt von Gott.« Gott lässt sich nicht zum Bösen verführen, und er verleitet auch niemanden zur Sünde. (<span class="t2">NLB</span> - <span class="t1">Jakobus 1:13</span>)<p>
												</p></li><li>Der große Drache ist niemand anders als der Teufel oder Satan, der als listige Schlange schon immer die ganze Welt zum Bösen verführt hat. Er wurde mit allen seinen Engeln aus dem Himmel auf die Erde hinuntergestürzt. Darum freut euch nun, ihr Himmel und alle, die ihr darin wohnt! Aber wehe euch, Erde und Meer! Der Teufel wurde auf euch losgelassen. Er schnaubt vor Wut; denn er weiß, dass ihm nicht mehr viel Zeit bleibt. (<span class="t2">HFA</span> - <span class="t1">Offenbarung 12:9,12</span>)<p>
												</p></li><li>Darauf führte ihn der Teufel hinauf und zeigte ihm auf einen Blick alle Reiche der Welt und sagte: »Ich will dir die Macht über alle diese Reiche in ihrer ganzen Größe und Pracht geben. Sie ist mir übertragen worden und ich kann sie weitergeben, an wen ich will.« (<span class="t2">GNB</span> - <span class="t1">Lukas 4:5,6</span>)<p>
												</p></li><li>Wir wissen, dass wir von Gott stammen; doch die ganze Welt ist in der Gewalt des Teufels. (<span class="t2">GNB</span> - <span class="t1">1. Johannes 5:19</span>)<p>
												</p></li><li>Um diese Zeit kamen die Jünger zu Jesus und fragten ihn: »Wer ist in der neuen Welt Gottes der Größte?« Da rief Jesus ein Kind herbei, stellte es in ihre Mitte und sagte: »Ich versichere euch: Wenn ihr euch nicht ändert und den Kindern gleich werdet, dann könnt ihr in Gottes neue Welt überhaupt nicht hineinkommen. Wer es auf sich nimmt, vor den Menschen so klein und unbedeutend dazustehen wie dieses Kind, ist in der neuen Welt Gottes der Größte.« (<span class="t2">GNB</span> - <span class="t1">Matthäus 18:1-4</span>)<p>
												</p></li><li>Einige Eltern brachten ihre Kinder zu Jesus, damit er sie segnete. Die Jünger aber wollten sie wegschicken. Als Jesus das merkte, wurde er zornig: "Lasst die Kinder zu mir kommen, und haltet sie nicht zurück, denn für Menschen wie sie ist Gottes neue Welt bestimmt." (<span class="t2">HFA</span> - <span class="t1">Markus 10:13,14</span>)<p>
												</p></li><li>Dann erzählte Jesus ein paar Leuten, die sehr selbstgerecht waren und alle anderen mit Geringschätzung behandelten, folgendes Gleichnis: »Zwei Männer gingen in den Tempel, um zu beten. Der eine war ein Pharisäer, der andere ein Steuereintreiber. Der stolze Pharisäer stand da und betete: `Ich danke dir, Gott, dass ich kein Sünder bin wie die anderen Menschen, wie die Räuber und die Ungerechten, die Ehebrecher oder besonders wie dieser Steuereintreiber da! Denn ich betrüge niemanden, ich begehe keinen Ehebruch, ich faste zwei Mal in der Woche und gebe dir regelmäßig den zehnten Teil von meinem Einkommen.´ Der Steuereintreiber dagegen blieb in einigem Abstand stehen und wagte nicht einmal den Blick zu heben, während er betete: `O Gott, sei mir gnädig, denn ich bin ein Sünder.´ Ich sage euch, dieser Sünder - und nicht der Pharisäer - kehrte heim als ein vor Gott Gerechtfertigter. 
												Denn die Stolzen werden gedemütigt, die Demütigen aber werden geehrt werden.« (<span class="t2">NLB</span> - <span class="t1">Lukas 18:9-14</span>)<p>
												</p></li><li>Wer hoch hinaus will, stürzt ab; Bescheidenheit bringt Ansehen. (<span class="t2">GNB</span> - <span class="t1">Sprüche 18:12</span>)<p>
												</p></li><li>Der Herr sagt: »Der Weise soll sich nicht wegen seiner Weisheit rühmen, der Starke nicht wegen seiner Stärke und der Reiche nicht wegen seines Reichtums. Grund sich zu rühmen hat nur, wer mich erkennt und begreift, was ich will. Denn ich bin der Herr, der Liebe, Recht und Treue auf der Erde schafft! An Menschen, die sich danach richten, habe ich Freude.« (<span class="t2">GNB</span> - <span class="t1">Jeremia 9:22,23</span>)<p>
												</p></li><li>Kennst du jemanden, der sich selbst für weise hält? Ich sage dir: Für einen Dummkopf gibt es mehr Hoffnung als für ihn! (<span class="t2">HFA</span> - <span class="t1">Sprüche 26:12</span>)<p>
												</p></li><li>Schlimm wird es denen ergehen, die sich in ihren Augen für weise und selbst für klug halten. (<span class="t2">NLB</span> - <span class="t1">Jesaja 5:21</span>)<p>
												</p></li><li>Denn es gibt keinen Menschen auf der Welt, der sich in allen Lebenslagen richtig verhält und niemals irgendetwas Schlechtes tut. (<span class="t2">NLB</span> - <span class="t1">Prediger 7:20</span>)<p>
												</p></li><li>Vergeltet anderen Menschen nicht Böses mit Bösem, sondern bemüht euch allen gegenüber um das Gute. Tragt euren Teil dazu bei, mit anderen in Frieden zu leben, so weit es möglich ist! Liebe Freunde, rächt euch niemals selbst, sondern überlasst die Rache dem Zorn Gottes. Denn es steht geschrieben: »Ich allein will Rache nehmen; ich will das Unrecht vergelten«, spricht der Herr. (<span class="t2">NLB</span> - <span class="t1">Römer 12:17-19</span>)<p>
												</p></li><li>Und sage nie: »Wie er zu mir war, so bin ich nun zu ihm; jetzt kann ich ihm alles heimzahlen!« (<span class="t2">NLB</span> - <span class="t1">Sprüche 24:29</span>)<p>
												</p></li><li>Warum regst du dich über einen Splitter im Auge deines Nächsten auf, wenn du selbst einen Balken im Auge hast? Mit welchem Recht sagst du: `Mein Freund, komm, ich helfe dir, den Splitter aus deinem Auge zu ziehen´, wenn du doch nicht über den Balken in deinem eigenen Auge hinaussehen kannst? (<span class="t2">NLB</span> - <span class="t1">Matthäus 7:3,4</span>)<p>
												</p></li><li>Mit welchem Recht verurteilst du also einen anderen Christen? Und warum schaust du auf ihn herab, nur weil er sich anders verhält? Wir werden alle einmal vor Gott stehen, und er wird über uns urteilen. So steht es in der Heiligen Schrift: "So wahr ich lebe, spricht der Herr: Vor mir werden alle niederknien, und alle werden bekennen, dass ich der Herr bin!" So wird also jeder für sich selbst vor Gott Rechenschaft ablegen müssen. (<span class="t2">HFA</span> - <span class="t1">Römer 14:10-12</span>)<p>
												</p></li><li>Nur Gott, der das Gesetz gegeben hat, kann gerecht richten. Nur er hat die Macht, zu retten oder zu vernichten. Welches Recht hast du also, deinen Nächsten zu verurteilen? (<span class="t2">NLB</span> - <span class="t1">Jakobus 4:12</span>)<p>
												</p></li><li>Verurteilt nicht andere, damit Gott nicht euch verurteilt! Denn euer Urteil wird auf euch zurückfallen, und ihr werdet mit demselben Maß gemessen werden, das ihr bei anderen anlegt. (<span class="t2">GNB</span> - <span class="t1">Matthäus 7:1,2</span>)<p>
												</p></li><li>»Werdet barmherzig, so wie euer Vater barmherzig ist! Verurteilt nicht andere, dann wird Gott auch euch nicht verurteilen. Sitzt über niemand zu Gericht, dann wird Gott auch über euch nicht zu Gericht sitzen. Verzeiht, dann wird Gott euch verzeihen. Schenkt, dann wird Gott euch schenken; ja, er wird euch so überreich beschenken, dass ihr gar nicht alles fassen könnt. Darum gebraucht anderen gegenüber ein reichliches Maß; denn Gott wird bei euch dasselbe Maß verwenden.« (<span class="t2">GNB</span> - <span class="t1">Lukas 6:36-38</span>)<p>
												</p></li><li>Wenn ihr denen vergebt, die euch Böses angetan haben, wird euer himmlischer Vater euch auch vergeben. Wenn ihr euch aber weigert, anderen zu vergeben, wird euer Vater euch auch nicht vergeben. (<span class="t2">NLB</span> - <span class="t1">Matthäus 6:14,15</span>)<p>
												</p></li><li>Man kann die neue Welt Gottes mit einem König vergleichen, der mit seinen Verwaltern abrechnen wollte. Zu ihnen gehörte ein Mann, der ihm einen Millionenbetrag schuldete. Aber er konnte diese Schuld nicht bezahlen. Deshalb wollte der König ihn, seine Frau, seine Kinder und seinen gesamten Besitz verkaufen lassen, um wenigstens einen Teil seines Geldes zu bekommen. Doch der Mann fiel vor dem König nieder und flehte ihn an: 'Herr, hab noch etwas Geduld! Ich will ja alles bezahlen.' Da hatte der König Mitleid. Er gab ihn frei und erließ ihm seine Schulden. Kaum war der Mann frei, ging er zu einem der anderen Verwalter, der ihm einen kleinen Betrag schuldete, packte ihn, würgte ihn und schrie: 'Bezahl jetzt endlich deine Schulden!' Da fiel der andere vor ihm nieder und bettelte: 'Hab noch etwas Geduld! Ich will ja alles bezahlen.' Aber der Verwalter wollte nicht warten und ließ ihn ins Gefängnis werfen, bis er alles bezahlt hätte. 
												Als nun die anderen sahen, was sich da ereignet hatte, waren sie empört und berichteten es dem König. Da ließ der König den Verwalter zu sich kommen und sagte: 'Was bist du doch für ein hartherziger Mensch! Deine ganze Schuld habe ich dir erlassen, weil du mich darum gebeten hast. Hättest du da nicht auch mit meinem anderen Verwalter Erbarmen haben können, so wie ich mit dir?' Zornig übergab er ihn den Folterknechten. Sie sollten ihn erst dann wieder freilassen, wenn er alle seine Schulden zurückgezahlt hätte. Auf die gleiche Art wird mein Vater im Himmel euch behandeln, wenn ihr euch weigert, eurem Bruder wirklich zu vergeben. (<span class="t2">HFA</span> - <span class="t1">Matthäus 18:23-35</span>)<p>
												</p></li><li>Seid freundlich und hilfsbereit zueinander und vergebt euch gegenseitig, was ihr einander angetan habt, so wie Gott euch durch Christus vergeben hat, was ihr ihm angetan habt. (<span class="t2">GNB</span> - <span class="t1">Epheser 4:32</span>)<p>
												</p></li><li>Wer selbst kein Erbarmen gehabt hat, über den wird auch Gott erbarmungslos Gericht halten. Wenn aber jemand barmherzig war, dann gilt: Das Erbarmen triumphiert über das Gericht. (<span class="t2">GNB</span> - <span class="t1">Jakobus 2:13</span>)<p>
												</p></li><li>Wer die Schwachen unterdrückt, beleidigt ihren Schöpfer. Wer Hilflosen beisteht, ehrt Gott. (<span class="t2">GNB</span> - <span class="t1">Sprüche 14:31</span>)<p>
												</p></li><li>Wer den Armen verspottet, beleidigt seinen Schöpfer; wer sich über das Unglück anderer freut, erhält seine Strafe. (<span class="t2">NLB</span> - <span class="t1">Sprüche 17:5</span>)<p>
												</p></li><li>Wer dem Armen hilft, leiht dem Herrn - und er wird ihm zurückgeben, was er Gutes getan hat! (<span class="t2">NLB</span> - <span class="t1">Sprüche 19:17</span>)<p>
												</p></li><li>Denkt daran, dass der Herr jeden von uns für das Gute belohnen wird, das wir tun, ob wir nun Sklaven sind oder frei. (<span class="t2">NLB</span> - <span class="t1">Epheser 6:8</span>)<p>
												</p></li><li>Vergesst nicht, Gutes zu tun und mit den anderen zu teilen, denn über solche Opfer freut sich Gott. (<span class="t2">NLB</span> - <span class="t1">Hebräer 13:16</span>)<p>
												</p></li><li>Denkt bei dem, was ihr tut, nicht nur an euch. Denkt vor allem an die anderen und daran, was für sie gut ist. (<span class="t2">HFA</span> - <span class="t1">1. Korinther 10:24</span>)<p>
												</p></li><li>Seid nicht selbstsüchtig; strebt nicht danach, einen guten Eindruck auf andere zu machen, sondern seid bescheiden und achtet die anderen höher als euch selbst. Denkt nicht nur an eure eigenen Angelegenheiten, sondern interessiert euch auch für die anderen und für das, was sie tun. (<span class="t2">NLB</span> - <span class="t1">Philipper 2:3,4</span>)<p>
												</p></li><li>Nehmt euch in Acht! Wenn ihr Gutes tut, dann tut es nicht öffentlich, nur damit ihr bewundert werdet. In diesem Fall dürft ihr nicht erwarten, von eurem Vater im Himmel belohnt zu werden. Wenn du einem Bedürftigen etwas gibst, posaune es nicht heraus, wie es die Heuchler tun, die in den Synagogen und auf den Straßen mit ihren Wohltaten angeben, nur um die Aufmerksamkeit auf sich zu ziehen! Ich versichere euch: Das ist der einzige Lohn, den sie jemals dafür erhalten werden. (<span class="t2">NLB</span> - <span class="t1">Matthäus 6:1,2</span>)<p>
												</p></li><li>Schließlich sagte Jesus zu seinem Gastgeber: "Zu einem Essen solltest du nicht deine Freunde, Geschwister, Verwandten oder die reichen Nachbarn einladen. Sie werden dir danken und dich wieder einladen. Dann hast du deine Belohnung schon gehabt. Bitte lieber die Armen, Verkrüppelten, Gelähmten und Blinden an deinen Tisch. Dann wirst du glücklich sein, denn du hast Menschen geholfen, die sich dir nicht erkenntlich zeigen können. Gott wird dich dafür belohnen, wenn er die von den Toten auferweckt, die nach seinem Willen gelebt haben." (<span class="t2">HFA</span> - <span class="t1">Lukas 14:12-14</span>)<p>
												</p></li><li>Glaubt ihr, ihr hättet dafür Anerkennung verdient, dass ihr die liebt, die euch auch lieben? Das tun sogar die Sünder! Und wenn ihr nur denen Gutes erweist, die euch Gutes tun, was ist daran so anerkennenswert? Selbst Sünder verhalten sich so! Oder wenn ihr nur denen Geld leiht, die es euch zurückzahlen können, was ist daran außergewöhnlich? Selbst Sünder leihen ihresgleichen Geld in der Hoffnung, die volle Summe zurückzuerhalten. Liebt eure Feinde! Erweist ihnen Gutes! Leiht ihnen Geld! Und macht euch keine Sorgen, weil sie es euch vielleicht nicht wiedergeben werden. Dann wird euer Lohn im Himmel groß sein und ihr handelt wirklich wie Kinder des Allerhöchsten, denn er erweist auch den Undankbaren und den Bösen Gutes. (<span class="t2">NLB</span> - <span class="t1">Lukas 6:32-35</span>)<p>
												</p></li><li>Fassen wir alles zusammen, so kommen wir zu dem Ergebnis: Nimm Gott ernst und befolge seine Gebote! Das ist alles, worauf es für den Menschen ankommt. Über alles, was wir tun, wird Gott Gericht halten, über die guten und die schlechten Taten, auch wenn sie jetzt noch verborgen sind. (<span class="t2">GNB</span> - <span class="t1">Prediger 12:13,14</span>)<p>
												</p></li><li>Denn wir alle müssen einmal vor Christus und seinem Richterstuhl erscheinen, wo alles ans Licht kommen wird. Dann wird jeder von uns das bekommen, was er für das Gute oder das Schlechte, das er in seinem Leben getan hat, verdient. (<span class="t2">NLB</span> - <span class="t1">2. Korinther 5:10</span>)<p>
												</p></li><li>Nichts in der ganzen Schöpfung ist vor ihm verborgen. Alles ist nackt und bloß vor den Augen Gottes, dem wir für alles Rechenschaft ablegen müssen. (<span class="t2">NLB</span> - <span class="t1">Hebräer 4:13</span>)<p>
												</p></li><li>Denn seine Augen wachen über die Wege des Menschen, er sieht alle seine Schritte. Es gibt keine Dunkelheit, und wäre sie auch noch so finster, in der sich der Übeltäter vor Gott verstecken könnte. (<span class="t2">NLB</span> - <span class="t1">Hiob 34:21,22</span>)<p>
												</p></li><li>Die Augen des Herrn sind überall; er sieht, ob jemand Unrecht oder das Rechte tut. (<span class="t2">GNB</span> - <span class="t1">Sprüche 15:3</span>)<p>
												</p></li><li>Er gibt jedem Menschen das, was er für seine Taten verdient hat. So wie jeder sein Leben führt, lässt Gott es ihm ergehen. (<span class="t2">NLB</span> - <span class="t1">Hiob 34:11</span>)<p>
												</p></li><li>Wer anderen eine Grube gräbt, sie aushöhlt, so tief er kann, der schaufelt sein eigenes Grab. Seine Bosheit fällt auf ihn selbst zurück, seine Untaten werden ihm zum Verhängnis. (<span class="t2">GNB</span> - <span class="t1">Psalm 7:16,17</span>)<p>
												</p></li><li>Der Tag des Herrn für alle Völker kommt bald! Wie du dich verhalten hast, so wird mit dir umgegangen werden. Deine Untaten werden auf dich selbst zurückfallen. (<span class="t2">NLB</span> - <span class="t1">Obadja 15</span>)<p>
												</p></li><li>Denn der Tag ist schon festgesetzt, an dem Gott alle Menschen richten wird; ja, er wird ein gerechtes Urteil sprechen durch den einen Mann, den er selbst dazu bestimmt hat. Das hat Gott bewiesen, indem er ihn von den Toten auferweckte. (<span class="t2">HFA</span> - <span class="t1">Apostelgeschichte 17:31</span>)<p>
												</p></li><li>Über die Frage, wann das geschehen wird, Brüder und Schwestern, zu welchem näheren Zeitpunkt es eintreten wird, brauchen wir euch nichts zu schreiben. Ihr wisst selbst ganz genau, dass der Tag des Herrn so unvorhergesehen kommt wie ein Dieb in der Nacht. Wenn die Menschen sagen werden: »Alles ist ruhig und sicher«, wird plötzlich Gottes vernichtendes Strafgericht über sie hereinbrechen, so wie die Wehen über eine schwangere Frau. Da gibt es kein Entrinnen. (<span class="t2">GNB</span> - <span class="t1">1. Thessalonicher 5:1-3</span>)<p>
												</p></li><li>Niemand weiß, wann das Ende kommen wird, weder die Engel im Himmel noch der Sohn. Den Tag und die Stunde kennt nur der Vater. Wenn der Menschensohn kommt, wird es auf der Erde zugehen wie zur Zeit Noahs, als die große Flut hereinbrach. Damals dachten die Menschen auch nur an Essen, Trinken und Heiraten. Selbst als Noah in die Arche stieg, glaubten die Leute nicht an das Unheil, bis die Flut sie alle mit sich riss. So wird es auch beim Kommen des Menschensohnes sein. (<span class="t2">HFA</span> - <span class="t1">Matthäus 24:36-39</span>)<p>
												</p></li><li>Auch die frühere Welt hat er nicht verschont - mit Ausnahme von Noah und den sieben Mitgliedern seiner Familie. Noah hatte die Welt vor dem gerechten Gericht Gottes gewarnt. Dann vernichtete Gott die Welt durch eine gewaltige Flut und alle gottlosen Menschen kamen darin um. Später legte er die Städte Sodom und Gomorra in Schutt und Asche und vertilgte sie vom Erdboden. An ihrem Beispiel zeigte er, wie es gottlosen Menschen ergehen wird. (<span class="t2">NLB</span> - <span class="t1">2. Petrus 2:5,6</span>)<p>
												</p></li><li>Deshalb seid wach und haltet euch bereit! Denn ihr wisst weder an welchem Tag noch zu welchem Zeitpunkt der Menschensohn kommen wird. (<span class="t2">HFA</span> - <span class="t1">Matthäus 25:13</span>)<p>
												</p></li><li>Doch vom Himmel her wird Gottes Zorn sichtbar über alle Gottlosigkeit und Ungerechtigkeit der Menschen, die die Wahrheit ablehnen. Dabei wissen sie von Gott; Gott selbst hat ihnen diese Erkenntnis gegeben. Seit Erschaffung der Welt haben die Menschen die Erde und den Himmel und alles gesehen, was Gott erschaffen hat, und können daran ihn, den unsichtbaren Gott, in seiner ewigen Macht und seinem göttlichen Wesen klar erkennen. Deshalb haben sie keine Entschuldigung dafür, von Gott nichts gewusst zu haben. (<span class="t2">NLB</span> - <span class="t1">Römer 1:18-20</span>)<p>
												</p></li><li>»Wenn aber der Verbrecher umkehrt und das Böse lässt, das er getan hat, wenn er alle meine Gebote befolgt und das Rechte tut, bleibt auch er am Leben und muss nicht sterben. All das Böse, das er früher getan hat, wird ihm nicht angerechnet. Weil er danach das Rechte getan hat, bleibt er am Leben. Meint ihr, ich hätte Freude daran, wenn ein Mensch wegen seiner Vergehen sterben muss?«, sagt Gott, der Herr. »Nein, ich freue mich, wenn er von seinem falschen Weg umkehrt und am Leben bleibt!« (<span class="t2">GNB</span> - <span class="t1">Hesekiel 18:21-23</span>)<p>
												</p></li><li>Der Mensch ist vergänglich wie das Gras, es ergeht ihm wie der Blume im Steppenland: Ein heißer Wind kommt - schon ist sie fort, und wo sie stand, bleibt keine Spur von ihr. (<span class="t2">GNB</span> - <span class="t1">Psalm 103:15,16</span>)<p>
												</p></li><li>Wie vergänglich ist doch der Mensch! Wie kurz ist sein Leben und wie viel Leid muss er tragen! Wie eine Blume blüht er für einen Augenblick auf und im nächsten ist er verwelkt. Er verschwindet wie ein Schatten und hat keinen Bestand. (<span class="t2">NLB</span> - <span class="t1">Hiob 14:1,2</span>)<p>
												</p></li><li>Wenn mir etwas ins Auge stach, was ich haben wollte, nahm ich es mir. Ich versagte mir keine einzige Freude. Und ich freute mich bei all den Mühen, die ich hatte - das war gleichsam ein Nebenlohn meiner Anstrengungen. Doch als ich alles prüfend betrachtete, was ich mir mit meinen Händen erworben hatte, und die Mühe dagegen hielt, die ich darauf verwendet hatte, merkte ich, dass alles sinnlos war. Es war so unnütz wie der Versuch, den Wind einzufangen. Es gibt keinen bleibenden Gewinn auf dieser Welt. (<span class="t2">NLB</span> - <span class="t1">Prediger 2:10,11</span>)<p>
												</p></li><li>Was hat ein Mensch davon, wenn er die ganze Welt gewinnt, aber zuletzt sein Leben verliert? (<span class="t2">GNB</span> - <span class="t1">Markus 8:36</span>)<p>
												</p></li><li>Es ist zum Verzweifeln! Wie er kam, muss er wieder gehen. Was hat er also von seiner harten Arbeit - es ist ja doch alles umsonst! (<span class="t2">HFA</span> - <span class="t1">Prediger 5:15</span>)<p>
												</p></li><li>Denn wir sind ohne Besitz auf diese Welt gekommen, und genauso werden wir sie auch wieder verlassen. Wenn wir zu essen haben und uns kleiden können, sollen wir zufrieden sein. (<span class="t2">HFA</span> - <span class="t1">1. Timotheus 6:7,8</span>)<p>
												</p></li><li>Deshalb fürchte dich nicht, wenn jemand reicher wird und sein Haus immer prachtvoller. Denn wenn er stirbt, nimmt er nichts davon mit, sein Reichtum folgt ihm nicht ins Grab. (<span class="t2">NLB</span> - <span class="t1">Psalm 49:17,18</span>)<p>
												</p></li><li>Wer am Geld hängt, bekommt nie genug davon. Wer Reichtum liebt, will immer noch mehr. Auch hier gilt: Alles vergeblich! (<span class="t2">GNB</span> - <span class="t1">Prediger 5:9</span>)<p>
												</p></li><li>Versuche nicht, mit aller Kraft reich zu werden; sei klug und vergeude deine Zeit nicht damit. Denn der Reichtum kann plötzlich verschwinden - er bekommt Flügel wie ein Adler und fliegt davon. (<span class="t2">NLB</span> - <span class="t1">Sprüche 23:4,5</span>)<p>
												</p></li><li>Verkauft, was ihr habt, und gebt es den Bedürftigen. Auf diese Weise sammelt ihr euch Schätze im Himmel! Und die Geldbörsen des Himmels haben keine Löcher. Dort ist euer Schatz sicher - kein Dieb kann ihn stehlen und keine Motte ihn zerfressen. (<span class="t2">NLB</span> - <span class="t1">Lukas 12:33</span>)<p>
												</p></li><li>Als Jesus weitergehen wollte, lief ein Mann auf ihn zu, warf sich vor ihm auf die Knie und fragte: "Guter Lehrer, was muss ich tun, um das ewige Leben zu bekommen?" Jesus entgegnete: "Weshalb nennst du mich gut? Es gibt nur einen, der gut ist, und das ist Gott. Du kennst doch seine Gebote: Du sollst nicht töten! Du sollst nicht die Ehe brechen! Du sollst nicht stehlen! Sag nichts Unwahres über deinen Mitmenschen! Du sollst nicht betrügen! Ehre deinen Vater und deine Mutter!" "Lehrer", antwortete der junge Mann, "an diese Gebote habe ich mich von Jugend an gehalten." Jesus sah ihn voller Liebe an: "Etwas fehlt dir noch: Verkaufe alles, was du hast, und gib das Geld den Armen. Damit wirst du im Himmel einen Reichtum gewinnen, der niemals verloren geht. Und dann komm und folge mir nach!" Über diese Forderung war der Mann tief betroffen. Traurig ging er weg, denn er war sehr reich. (<span class="t2">HFA</span> - <span class="t1">Markus 10:17-22</span>)<p>
												</p></li><li>Dann wandte er sich an alle: "Hütet euch vor der Habgier! Wenn jemand auch noch so viel Geld hat, das Leben kann er sich damit nicht kaufen." An einem Beispiel erklärte er seinen Zuhörern, was er damit meinte: "Ein reicher Gutsbesitzer hatte eine besonders gute Ernte. Er überlegte: 'Wo soll ich bloß alles unterbringen? Meine Scheunen sind voll; da geht nichts mehr rein.' Er beschloss: 'Ich werde die alten Scheunen abreißen und neue bauen, so groß, dass ich das ganze Getreide, ja alles, was ich habe, darin unterbringen kann. Dann will ich mich zur Ruhe setzen. Ich habe für lange Zeit ausgesorgt. Jetzt lasse ich es mir gut gehen. Ich will gut essen und trinken und mein Leben genießen!' Aber Gott sagte zu ihm: 'Du Narr! Noch in dieser Nacht wirst du sterben. Wer bekommt dann deinen ganzen Reichtum, den du angehäuft hast?' So wird es allen gehen, die auf der Erde Reichtümer sammeln, aber mit leeren Händen vor Gott stehen." (<span class="t2">HFA</span> - <span class="t1">Lukas 12:15-21</span>)<p>
												</p></li><li>Hört auf, diese Welt und das, was sie euch anbietet, zu lieben! Denn wer die Welt liebt, zeigt, dass die Liebe des Vaters nicht in ihm ist. Denn die Welt kennt nur das Verlangen nach körperlicher Befriedigung, die Gier nach allem, was unsere Augen sehen, und den Stolz auf unseren Besitz. Dies alles ist nicht vom Vater, sondern kommt von der Welt. Doch diese Welt vergeht mit all ihren Verlockungen. Aber wer den Willen Gottes tut, wird in Ewigkeit leben. (<span class="t2">NLB</span> - <span class="t1">1. Johannes 2:15-17</span>)<p>
												</p></li><li>Wer sein Leben in dieser Welt liebt, wird es verlieren. Wer sein Leben in dieser Welt gering achtet, wird es zum ewigen Leben bewahren. (<span class="t2">NLB</span> - <span class="t1">Johannes 12:25</span>)<p>
												</p></li><li>Die Lebenden wissen wenigstens, dass sie einmal sterben müssen. Die Toten wissen überhaupt nichts mehr. Ihre Verdienste werden nicht belohnt; denn niemand denkt mehr an sie. (<span class="t2">GNB</span> - <span class="t1">Prediger 9:5</span>)<p>
												</p></li><li>Alles, was du tun kannst, wozu deine Kraft ausreicht, das tu! Denn im Totenreich, wohin auch du gehen wirst, gibt es weder Tun noch Denken, weder Erkenntnis noch Weisheit. (<span class="t2">HFA</span> - <span class="t1">Prediger 9:10</span>)<p>
												</p></li><li>Der Tod ist durch die Schuld eines einzigen Menschen in die Welt gekommen. Ebenso kommt auch durch einen einzigen die Auferstehung. Alle Menschen müssen sterben, weil sie Nachkommen Adams sind. Ebenso werden alle durch die Verbindung mit Christus zu neuem Leben auferweckt. (<span class="t2">HFA</span> - <span class="t1">1. Korinther 15:21,22</span>)<p>
												</p></li><li>Wundert euch nicht! Die Zeit wird kommen, in der die Toten in ihren Gräbern die Stimme des Sohnes Gottes hören und auferstehen werden. Diejenigen, die Gutes getan haben, werden zum ewigen Leben auferstehen, und diejenigen, die Schlechtes getan haben, werden zum Gericht auferstehen. (<span class="t2">NLB</span> - <span class="t1">Johannes 5:28,29</span>)<p>
												</p></li><li>Wie meine Ankläger habe ich die Hoffnung, dass Gott alle Menschen vom Tod auferwecken wird - sowohl die Menschen, die ihm gedient haben, als auch die anderen, die nichts von ihm wissen wollten. (<span class="t2">HFA</span> - <span class="t1">Apostelgeschichte 24:15</span>)<p>
												</p></li><li>Dann können die Blinden wieder sehen und die Tauben wieder hören. Dann springt der Gelähmte wie ein Hirsch und der Stumme jubelt vor Freude. In der Wüste brechen Quellen auf und Bäche ergießen sich durch die Steppe. (<span class="t2">GNB</span> - <span class="t1">Jesaja 35:5,6</span>)<p>
												</p></li><li>Sie leiden weder Hunger noch Durst, Hitze und Sonnenglut schadet ihnen nicht. Denn ich habe Erbarmen mit ihnen und führe sie zu sprudelnden Quellen. (<span class="t2">HFA</span> - <span class="t1">Jesaja 49:10</span>)<p>
												</p></li><li>Er wird alle ihre Tränen abwischen. Es wird keinen Tod mehr geben und keine Traurigkeit, keine Klage und keine Quälerei mehr. Was einmal war, ist für immer vorbei. (<span class="t2">GNB</span> - <span class="t1">Offenbarung 21:4</span>)<p>
												</p></li><li>Kein Mensch im Land wird noch klagen, er sei von Krankheit und Schwäche geplagt; denn die Schuld des Volkes ist vergeben. (<span class="t2">GNB</span> - <span class="t1">Jesaja 33:24</span>)<p>
												</p></li><li>Dann wird dein Körper wieder frisch und stark, genauso wie in deiner Jugendzeit. (<span class="t2">GNB</span> - <span class="t1">Hiob 33:25</span>)<p>
												</p></li><li>Dann werden der Wolf und das Lamm einträchtig zusammenleben; der Leopard und die Ziege werden beieinander lagern. Kalb, Löwe und Mastvieh werden Freunde und ein kleiner Junge wird sie hüten. Kuh und Bär werden miteinander weiden. Ihre Jungen werden nebeneinander ruhen. Der Löwe wird Stroh fressen wie das Vieh. Der Säugling spielt am Schlupfloch der Otter. Ja, ein Kleinkind steckt seine Hand in eine Giftschlangenhöhle. Auf meinem ganzen heiligen Berg wird niemand mehr etwas Böses tun oder Unheil stiften, denn wie das Wasser das Meer füllt, so wird die Erde mit der Erkenntnis des Herrn erfüllt sein. (<span class="t2">NLB</span> - <span class="t1">Jesaja 11:6-9</span>)
												</li></ol>

												<a target="_blank" href="http://www.bibleserver.com" class="l">Quelle www.BIBLESERVER.com</a>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="footer">

			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="well">
							<h4>Impressum</h4>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- load js last -->
		<script src="http://www.bc547.de/infotechnik/js/jquery.min.js"></script>
		<script src="http://www.bc547.de/infotechnik/js/bootstrap.min.js"></script>
		<script src="//google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>

	</body>
</html>